<?php
/**
 * plusPHP FrameWork
 * @File name: HttpNotFoundException.php
 * @Author: Naizui_ycx
 * @Email: chenxi2511@qq.com
 * @Date: 2018/6/7
 * @Time: 21:54
 * @Description: http未找到异常
 */

namespace plusPHP\Exception;

class HttpNotFoundException extends HttpException
{

    protected $_httpCode = 404;

    protected $_httpContents = [
        'title' => 'NOT FOUND',
        'content' => 'PAGE NOT FOUND!'
    ];


    public function resetContent()
    {
        parent::resetContent(); // TODO: Change the autogenerated stub
        $this->setContents([
            'title' => 'NOT FOUND',
            'content' => 'PAGE NOT FOUND!'
        ]);
    }

}