<?php
/**
 * plusPHP FrameWork
 * @File name: HttpForbiddenException.php.
 * @Author: Naizui_ycx
 * @Email: chenxi2511@qq.com
 * @Date: 2018/6/8
 * @Time: 9:55
 * @Description: http无权限异常
 */
namespace plusPHP\Exception;


class HttpForbiddenException extends HttpException
{

    protected $_httpCode = 403;

    protected $_httpContents = [
        'title' => '403 FORBIDDEN',
        'content' => '403 FORBIDDEN!'
    ];


    public function resetContent()
    {
        parent::resetContent(); // TODO: Change the autogenerated stub
        $this->setContents([
            'title' => '403 FORBIDDEN',
            'content' => '403 FORBIDDEN!'
        ]);
    }

}